package dev.dkutko.owlnest.media.controller;

import dev.dkutko.owlnest.media.domain.ManagedMediaPurpose;
import dev.dkutko.owlnest.media.service.CreatedMediaUpload;
import io.swagger.v3.oas.annotations.media.Schema;

import java.net.URI;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

public record MediaUploadResponse(
        @Schema(example = "47c62a2c-ae5f-48d1-b05c-126cc1292392")
        UUID mediaId,

        @Schema(example = "AVATAR")
        ManagedMediaPurpose purpose,

        @Schema(example = "image/webp")
        String contentType,

        @Schema(example = "524288")
        long sizeBytes,

        @Schema(description = "Upload lifecycle state", allowableValues = "PENDING_UPLOAD")
        String state,

        UploadAuthorization upload
) {

    private static final String PENDING_UPLOAD = "PENDING_UPLOAD";

    static MediaUploadResponse from(CreatedMediaUpload upload) {
        return new MediaUploadResponse(
                upload.mediaId(),
                upload.purpose(),
                upload.contentType(),
                upload.sizeBytes(),
                PENDING_UPLOAD,
                new UploadAuthorization(
                        "PUT",
                        upload.uploadUrl(),
                        upload.requiredHeaders(),
                        upload.uploadExpiresAt()
                )
        );
    }

    public record UploadAuthorization(
            @Schema(allowableValues = "PUT", example = "PUT")
            String method,

            @Schema(description = "Short-lived private R2 upload capability", format = "uri")
            URI url,

            @Schema(
                    description = "Headers the client must set exactly. Content-Length is also signed to sizeBytes "
                            + "but is generated by the HTTP transport and must not be set manually in Flutter Web.",
                    example = "{\"Content-Type\":\"image/webp\",\"If-None-Match\":\"*\"}"
            )
            Map<String, String> requiredHeaders,

            Instant expiresAt
    ) {
    }
}
